version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: routewise
      POSTGRES_PASSWORD: routewisepass
      POSTGRES_DB: routewise
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - routewise-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@routewise.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - routewise-network
    depends_on:
      - db

  backend:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - routewise-network

networks:
  routewise-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local
